theme: jekyll-theme-cayman
title: DIRI Lab 2020
SEOTitle: 武子越的博客 | WU ZIYUE's Blog
header-img: img/A.jpg
email: wuziyue@zju.edu.cn
description: "Learn By Doing, Keep Your Hands Dirty."
keyword: "ZIYUE WU"
url: "http://Tinky2013.github.io/Self"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
